gitrosetta/urls.py
#
# Copyright 2017, Martin Owens <doctormo@gmail.com>
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#
"""
The default urls for gitr have a namespace built in and it doesn't
need to be specified in your urls.py file, only include access.
"""

from django.conf.urls import patterns, url, include

from .views import *

def url_tree(regex, *urls, **kw):
    return url(regex, include(patterns('', *urls), **kw))

urlpatterns = patterns('gitrosetta.views', url_tree('',
  url(r'^$',                  HomePage.as_view(), name='home'),
  url(r'^all/(?P<lang>[\w-]+)/$', AllLanguages.as_view(), name='language'),
  url_tree(r'^(?P<slug>[\w-]+)/',
    url(r'^$',                Repository.as_view(), name='repository'),
    url(r'^hook/$',           GitWebHook.as_view(), name='git-hook'),
    url_tree(r'^(?P<lang>.*)/',
      url(r'^$',              TranslateLanguage.as_view(), name='translate'),
      url(r'^download/$',     DownloadLanguage.as_view(), name='download'),
      url(r'^upload/$',       UploadLanguage.as_view(), name='upload'),
    ),
  ),
namespace="gitr"))

gitrosetta/templates/gitrosetta/base.html
<!DOCTYPE html> 
<html xmlns="http://www.w3.org/1999/xhtml" lang="{{ language }}">
  {% load i18n static %}
  <head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />

    <title>{% block pagetitle %}{{ title|default:"Home" }} | Git Rosetta{% endblock %}</title>

    <link rel="shortcut icon" type="image/png" href="{% static 'images/gitr/icon.png' %}" />
    <link rel="stylesheet" type="text/css" href="{% static 'css/gitrosetta.css' %}" />
    <script src="{% static 'admin/js/jquery.min.js' %}" type="text/javascript"></script>

    {% block "head" %}{% endblock %}
  </head>

  <body id="{% block sectionid %}generic{% endblock %}">
    <div class="page-center-wrap">
      <div class="page-center-content">
        <div id="header">
          <div id="navigation">
            <ul>
              <li><a href="">Subscribe</a></li>
            </ul>
          </div>
          <div id="title">
            {% if language %}
              <a href="{% url "gitr:list" %}"><img src="{% static language_logo %}" id="brand" title="CMS Rosetta Translations"/>
              {{ language_namo }} {% trans "Translations" %}</a>
            {% else %}
              <a href="{% url "gitr:home" %}"><img src="{% static "images/gitr/logo.svg" %}" id="brand" style="width: 48px; height: 48px; top: -16px;" title="CMS Rosetta Translations"/>
                {{ title|default:"Git Rosetta" }}</a>
            {% endif %}
          </div>
        </div>

    {% if messages %}
      <ul id="messages">{% for message in messages %}<li{% if message.tags %} class="{{ message.tags }}"{% endif %} title="{{ message.tags }}">
        {% if 'safe' in message.tags %}{{ message|safe }}{% else %}{{ message }}{% endif %}
      </li>{% endfor %}</ul>
    {% endif %}

        <div id="actions">
          <ul>
            <li><a href="{% url "gitr:home" %}">{% trans "Language" %}</a></li>
            {% if language %}
              <li><a href="{% url "gitr:list" %}">{{ language_name }}</a></li>
            {% endif %}
            {% block breadcumbs %}{% endblock %}
          </ul>
          <div class="clear"></div>
        </div>
        <div id="content-wrap">
          {% block main %}{% endblock %}
        </div>
        <div id="footer">
          <p><a href="https://gitlab.com/doctormo/git-rosetta">Git Rosetta</a> by <a href="http://divajutta.com/doctormo/">Martin Owens</a> - AGPLv3 Free Software Project</p>
        </div>
      </div>
    </div>
  </body>
</html>

gitrosetta/templates/gitrosetta/translationrepository_detail.html
{% extends "gitrosetta/base.html" %}
{% load i18n static gitrosetta %}

{% block title %}
  {% block pagetitle %}{% trans "Translation Statistics" %}{% endblock %}
{% endblock %}

{% block main %}
  <div id="content">
    <table class="list">
      <thead>
        <tr>
          <th>&nbsp;</th>
          <th>{% trans "Language" %}</th>
          <th colspan="3">{% trans "Progress" %}</th>
          <th>{% trans "Contributors" %}</th>
        </tr>
      </thead>
      <tbody>
        {% for lang in object_list %}
            </tr>
            {% if lang.icon %}
              <td style="width: 22px; text-align: right;"><img src="{{ lang.icon.url }}"/></td>
            {% else %}
              <td style="width: 22px; text-align: right;"><img src="{% static "images/lang.svg" %}"/></td>
            {% endif %}

            <td><a href="/{{ lang.id }}{{ current }}{{ kind|default:"all" }}/">{% trans lang.name %}</a></td>

            {% progressbar lang.progress %}
            
            <td>{{ lang.people|join:', ' }}</td>
          <tr>
        {% endfor %}
      </tbody>
    </table>
  </div>
  <!--div id="sidebar">
    <h2>Filter</h2>
    <ul class="object-tools">
      <li{% if not kind %} class="active"{% endif %}>
        <a href="?filter=all">{% trans "All" %}</a>
      </li>
      {% for k in kinds %}
        <li{% if kind == k %} class="active"{% endif %}>
          <a href="?filter={{ k }}">{% trans k|title %}</a>
        </li>
      {% endfor %}
    </ul>
  </div-->
{% endblock %}

gitrosetta/templates/gitrosetta/translationrepository_list.html
{% extends "gitrosetta/base.html" %}
{% load i18n gitrosetta future %}

{% block breadcumbs %}
  {% if kind %}<li><a>{% trans kind|title %} Translations</a></li>{% endif %}
{% endblock %}

{% block main %}
  <div id="content">
      <h2>{% trans "All Repositories" %}</h2>
      <table class="list">
        <thead>
          <tr>
            <th>{% trans "Project Repository" %}</th>
            <th colspan="3">{%trans "Progress" %}</th>
            <th>{% trans "Location" %}</th>
          </tr>
        </thead>
        <tbody>
          {% for repo in object_list %}
            <tr class="{% cycle "row1" "row2" %}">
              <td><a href="{{ repo.get_absolute_url }}">{{ repo }}</a></td>
              {% progressbar repo.progress %}
              <td class="hint">{{ repo.git_url }}</td>
            </tr>
          {% endfor %}
        </tbody>
      </table>
  </div>
  <!--div id="sidebar">
    <h2>Filter</h2>
    <ul class="object-tools">
        <li{% if not kind %} class="active"{% endif %}>
          <a href="{% url 'gitr:home' %}">{% trans "All" %}</a>
        </li>
        {% for k in kinds %}
          <li{% if kind == k %} class="active"{% endif %}>
            <a href="{% url 'gitr:home' k %}">{% trans k|title %}</a>
          </li>
        {% endfor %}
    </ul>
  </div-->
{% endblock %}