gitrosetta/urls.py
#
# Copyright 2017, Martin Owens <doctormo@gmail.com>
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#
"""
The default urls for gitr have a namespace built in and it doesn't
need to be specified in your urls.py file, only include access.
"""

from django.conf.urls import patterns, url, include

from .views import *

def url_tree(regex, *urls, **kw):
    return url(regex, include(patterns('', *urls), **kw))

urlpatterns = patterns('gitrosetta.views', url_tree('',
  url(r'^$',                  HomePage.as_view(), name='home'),
  url(r'^all/(?P<lang>[\w-]+)/$', AllLanguages.as_view(), name='language'),
  url_tree(r'^(?P<slug>[\w-]+)/',
    url(r'^$',                Repository.as_view(), name='repository'),
    url(r'^hook/$',           GitWebHook.as_view(), name='git-hook'),
    url_tree(r'^(?P<lang>.*)/',
      url(r'^$',              TranslateLanguage.as_view(), name='translate'),
      url(r'^download/$',     DownloadLanguage.as_view(), name='download'),
      url(r'^upload/$',       UploadLanguage.as_view(), name='upload'),
    ),
  ),
namespace="gitr"))

gitrosetta/templates/gitr/item.html
{% extends "gitrosetta/base.html" %}
{% load admin_static %}
{% load future rosetta i18n %}

{% block header %}
  {{ block.super }}
  <div id="user-tools">
    <p>
      <span>
        <a href="{% url 'gitr:upload' pofile.app.kind pofile.app.name %}">{% trans "Upload catalog" %}</a> /
        <a href="{% url 'gitr:download' pofile.app.kind pofile.app.name %}">{% trans "Download this catalog" %}</a>
      </span>
    </p>
  </div>
{% endblock %}

{% block pagetitle %}{{ block.super }}
  - {{ pofile.app.kind|title }}
  - {{ pofile.app.name|title }}
({{ pofile.percent_translated|floatformat:0 }}%){% endblock %}

{% block breadcumbs %}
  <li><a href="{% url 'gitr:list' pofile.app.kind %}">{{ pofile.app.kind|title }}</a></li>
  <li><a>{{ pofile.app.name|title }}</a></li>
{% endblock %}

{% block main %}

  <script>
    $(document).ready(function() {
      $('.show_more').click(function() {
        $(this).parent().prev().toggleClass('visible');
      });
    });
  </script>

  <div id="topbar">
    <form class="search" method="post" action="">
      {% if query %}
        <a class="clear" href="{{ clear_url }}"><img title="{% trans "Clear Search" %}" src="{% static "images/rosetta/clear.svg" %}"/></a>
      {% endif %}
      {% csrf_token %}
      <input type="text" name="query" value="{{ query|default:'' }}" placeholder="Search" {% if query %}style="margin-right: -25px;"{% endif %}/>
    </form>
    <ul>
      {% for fid, name in pofile.filters %}
        <li{% if filter == fid %} class="active"{% endif %}>
          <a href="?filter={{ fid }}">{% trans name %}</a>
        </li>
      {% endfor %}
    </ul>
  </div>

  {% autopaginate entries msg_per_page as items %}

      <form method="post" action="">
        <table class="list">
          <thead>
            <tr>
              {% rosetta_csrf_token %}
              <th><div class="text">{% trans "Original" %}</div></th>
              <th>{{ language_name }}</th>
              <th class="c fuzzy"><span class="checkall"></span> {% trans "Fuzzy" %}</th>
              <th class="occur">{% trans "Occurrences(s)" %}</th>
            </tr>
          </thead>
          <tbody>
            {% for message in items %}
              <tr class="{% cycle "row1" "row2" %}">
                {% if message.msgid_plural %}
                  <td class="original plural">
                    <div class="plural-container">
                      <span class="part">{{message.msgid|format_message|linebreaksbr}}</span>
                      <span class="part">{{message.msgid_plural|format_message|linebreaksbr}}</span>
                    </div>

                    {% if message.msgctxt %}
                      <span class="context">{% trans "Context hint" %}: {{message.msgctxt|safe}}</span>
                    {% else %}
                      {% if message.comment %}
                        <span class="context">{% trans "Context hint" %}: {{message.comment|safe}}</span>
                      {% endif %}
                    {% endif %}
                  </td>
                  <td class="translation">
                    {% for k, msgstr in message.msgstr_plural.items|dictsort:"0"  %}
                      <label for="m_{{message.md5hash}}_{{k}}">{{k}}:</label>
                      <textarea rows="{{message.msgid|format_message|lines_count}}" cols="40" id="{{ message.md5hash }}_msg_{{ k }}" name="{{ message.md5hash }}_msgs_{{ k }}" tabindex="{% increment tab_idx %}">{{msgstr}}</textarea>
                    {% endfor %}
                  </td>
                {% else %}
                  <td class="original">
                    <span class="message">{{ message.msgid|format_message|linebreaksbr }}</span>
                    {% if message.msgctxt %}
                      <span class="context">{% trans "Context hint" %}: "{{message.msgctxt|safe}}"</span>
                    {% else %}
                      {% if message.comment %}
                        <span class="context">{% trans "Context hint" %}: {{message.comment|safe}}</span>
                      {% endif %}
                    {% endif %}
                  </td>
                  <td class="translation">
                    {% if message.is_short %}
                      <input name="{{ message.md5hash }}" value="{{ message.msgstr }}" tabindex="{% increment tab_idx %}"/>
                    {% else %}
                      <textarea rows="{{message.msgid|format_message|lines_count}}" name="{{ message.md5hash }}_msg" tabindex="{% increment tab_idx %}">{{message.msgstr}}</textarea>
                    {% endif %}
                    {% if ENABLE_TRANSLATION_SUGGESTIONS %}
                      <a href="#" class="suggest">{% trans "suggest" %}</a>
                    {% endif %}
                  </td>
                {% endif %}
                <td class="c">
                  <input type="checkbox" name="{{message.md5hash}}_fuzzy" value="1" {% if message|is_fuzzy %}checked="checked"{% endif %} />
                </td>
                <td class="location">
                  {% for fn,lineno in message.occurrences_trim %}
                    <code{% if forloop.counter|gt:1 %} class="hide"{% endif %}>{{ fn }}:{{lineno}}</code>
                  {% endfor %}
                </td>
                <td>
                  {% if message.occurrences|length|gt:1 %}
                    <a href="#" class="show_more">...</a>
                  {% endif %}
                </td>
              </tr>
            {% endfor %}
          </tbody>
        </table>
        {% if query %}<input type="hidden" name="query" value="{{ query }}"/>{% endif %}
        <div id="submit-row">
          {% paginate %}
          {% if page_obj.has_next %}
            <button type="submit" class="button default" tabindex="{% increment tab_idx %}" style="float: right;" name="save" value="{{ page|add:1 }}">{% trans "save and next" %} ››</button>
          {% else %}
            <button type="submit" class="button default" tabindex="{% increment tab_idx %}" style="float: right;" name="save" value="0">{% trans "save and quit" %}</button>
            {% endif %}
          </button>
        </div>
      </form>
    </div>

{% endblock %}

gitrosetta/templates/gitr/pagination.html
{% load i18n %}

{% if is_paginated %}
  {% if page_obj.has_previous %}
    <button class="prev default button" name="page" value="{{ page_obj.previous_page_number }}">&lsaquo;&lsaquo; {% trans "previous" %}</button>
  {% else %}
    <button class="prev default button" disabled>&lsaquo;&lsaquo; {% trans "previous" %}</button>
  {% endif %}

  {% for page in pages %}
    {% if page %}
      {% ifequal page page_obj.number %}
        <button class="current default button" disabled>{{ page }}</button>
      {% else %}
        <button class="page default button" name="page" value="{{ page }}">{{ page }}</button>
      {% endifequal %}
    {% else %}
      <button class="dot default button" disabled>...</button>
    {% endif %}
  {% endfor %}

{% endif %}

gitrosetta/templates/gitr/progress.html
{% if done %}
  <td class="ch-total r">{{ done.total }}/{{ all.total }}</td>
  <td class="ch-progress r">{{ done.percent|floatformat:0 }}%</td>
  <td title="{% for k,v in keys.items %}{% if v.name %}{{ v.name }}: {{ v.total }} ({{ v.percent|floatformat:0 }}%)
{% endif %}{% endfor %}">
    <meter value="{{ done.percent }}" min="0" low="30" optimum="95" high="90" max="100"></meter>
  </td>
{% else %}
  <td class="ch-total r">?/?</td>
  <td class="ch-progress r">0%</td>
  <td><meter value="0" min="0" low="0" optimum="0" high="0" max="100" style="opacity: 0.5;"></meter></td>
{% endif %}

gitrosetta/templates/gitr/webhook.html
1